version: "3.3"
services:
  spark-master:
    image: spark-master
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-net
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
  spark-worker:
    image: spark-worker
    depends_on:
      - spark-master
    ports:
      - 8080
    networks:
      - spark-net
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8080"
networks:
  spark-net:
    driver: bridge
    ipam:
      driver: default
